language: python
python:
  - "2.7"

install:
  - pip install django django-nose coverage coveralls

script: coverage run --source="." manage.py test desirables
after_success: coveralls

branches:
  only:
    - master
    - testing