language: python
python:
  - "2.7"

install:
  - pip install django django-nose coverage coveralls
  - apt-get install imagemagick
  - ./test_setup.sh

script: coverage run --source="desirables" --omit="*/tests.py,*/apps.py,*/migrations/*" manage.py test desirables
after_success: coveralls

branches:
  only:
    - master
    - testing